---
version: "2"
services:
  tvheadend-status:
    image: git-developer/tvheadend-status:latest
    container_name: tvheadend-status
    environment:
#      Supported environment variables with default values: 
#      - TZ=<no default>
#      - TVHEADEND_USER=<no default>
#      - TVHEADEND_PASSWORD=<no default>
#      - TVHEADEND_HOST=<no default>
#      - TVHEADEND_HTTP_PORT=9981
#      - TVHEADEND_HTTP_URL=http://${TVHEADEND_IP}:${TVHEADEND_HTTP_PORT}
#      - TVHEADEND_HTTP_TIMEOUT=15
#      - MQTT_BROKER_HOSTNAME=<no default>
#      - MQTT_TOPIC_PREFIX=tvheadend
    volumes:
      - ./markers:/app/markers
