---
version: "2"
services:
  tvheadend-mqtt:
    image: ckware/tvheadend-mqtt:latest
    container_name: tvheadend-mqtt
    environment:
#      Required environment variables:
#      - TVHEADEND_USER=hts
#      - TVHEADEND_PASSWORD=hts
#      - TVHEADEND_HOST=localhost
#      - MQTT_BROKER_HOSTNAME=localhost
    volumes:
       #  support for publishing triggered by Tvheadend (optional)
#      - /home/hts/markers:/app/markers
       # support for user-defined plugins (optional)
#      - ./plugins:/app/plugins
    restart: unless-stopped
